/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PulsarFitterGui.java
 *
 * Created on 16/12/2009, 13:08:54
 */
package pulsarfitter;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;
import javax.swing.SwingUtilities;
import pulsarhunter.displaypanels.MKPlot;
import pulsarhunter.displaypanels.PlotOneDim;

/**
 *
 * @author kei041
 */
public class PulsarFitterGui extends javax.swing.JFrame {

    private PulsarFitter fitter;
    private double prevStart = 0;
    private double prevEnd = 0;

    /** Creates new form PulsarFitterGui */
    public PulsarFitterGui() {
        initComponents();
        fitter = new PulsarFitter();
        replot();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int sh = screenSize.height;
        int sw = screenSize.width;
        if (sw > 2 * sh) {
            sw /= 2;
        }
        setBounds((sw - 1024) / 2, (sh - 768) / 2, 1024, 768);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_plot = new javax.swing.JPanel();
        jPanel_head = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_par = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jTextField_per = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel_left = new javax.swing.JPanel();
        jPanel_params = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_epoch = new javax.swing.JTextField();
        jCheckBox_epoch = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField_period = new javax.swing.JTextField();
        jCheckBox_period = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField_pdot = new javax.swing.JTextField();
        jCheckBox_pdot = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField_pb = new javax.swing.JTextField();
        jCheckBox_pb = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField_x = new javax.swing.JTextField();
        jCheckBox_x = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField_tasc = new javax.swing.JTextField();
        jCheckBox_tasc = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jTextField_omega = new javax.swing.JTextField();
        jCheckBox_omega = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField_ecc = new javax.swing.JTextField();
        jCheckBox_ecc = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField_start = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jTextField_end = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jRadioButton_start = new javax.swing.JRadioButton();
        jRadioButton_end = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_plot.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel_plot, java.awt.BorderLayout.CENTER);

        jPanel_head.setLayout(new javax.swing.BoxLayout(jPanel_head, javax.swing.BoxLayout.LINE_AXIS));

        jLabel9.setText("Load Par File:");
        jPanel_head.add(jLabel9);
        jPanel_head.add(jTextField_par);

        jButton4.setText("Load");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel_head.add(jButton4);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setMaximumSize(new java.awt.Dimension(0, 1000));
        jSeparator1.setMinimumSize(new java.awt.Dimension(20, 10));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 10));
        jPanel_head.add(jSeparator1);

        jLabel10.setText("Loat Per File:");
        jPanel_head.add(jLabel10);
        jPanel_head.add(jTextField_per);

        jButton5.setText("Load");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel_head.add(jButton5);

        getContentPane().add(jPanel_head, java.awt.BorderLayout.NORTH);

        jPanel_left.setLayout(new java.awt.BorderLayout());

        jPanel_params.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel_params.setPreferredSize(new java.awt.Dimension(300, 200));

        jLabel6.setText("Epoch");
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel6);

        jTextField_epoch.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_epoch.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_epoch);

        jCheckBox_epoch.setText("Fit");
        jPanel_params.add(jCheckBox_epoch);

        jLabel1.setText("Period");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel1);

        jTextField_period.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_period.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_period);

        jCheckBox_period.setText("Fit");
        jPanel_params.add(jCheckBox_period);

        jLabel2.setText("P dot");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel2);

        jTextField_pdot.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_pdot.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_pdot);

        jCheckBox_pdot.setText("Fit");
        jPanel_params.add(jCheckBox_pdot);

        jLabel3.setText("P binary");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel3);

        jTextField_pb.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_pb.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_pb);

        jCheckBox_pb.setText("Fit");
        jPanel_params.add(jCheckBox_pb);

        jLabel4.setText("a sin(i)");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel4);

        jTextField_x.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_x.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_x);

        jCheckBox_x.setText("Fit");
        jPanel_params.add(jCheckBox_x);

        jLabel5.setText("Tasc");
        jLabel5.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel5);

        jTextField_tasc.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_tasc.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_tasc);

        jCheckBox_tasc.setText("Fit");
        jPanel_params.add(jCheckBox_tasc);

        jLabel7.setText("Omega");
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel7);

        jTextField_omega.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_omega.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_omega);

        jCheckBox_omega.setText("Fit");
        jPanel_params.add(jCheckBox_omega);

        jLabel8.setText("Ecc");
        jLabel8.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel8);

        jTextField_ecc.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_ecc.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_ecc);

        jCheckBox_ecc.setText("Fit");
        jPanel_params.add(jCheckBox_ecc);

        jLabel11.setText("Start");
        jLabel11.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel11);

        jTextField_start.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_start.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_start);

        jSeparator2.setPreferredSize(new java.awt.Dimension(41, 23));
        jPanel_params.add(jSeparator2);

        jLabel12.setText("End");
        jLabel12.setPreferredSize(new java.awt.Dimension(60, 25));
        jPanel_params.add(jLabel12);

        jTextField_end.setMaximumSize(new java.awt.Dimension(200, 20));
        jTextField_end.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel_params.add(jTextField_end);

        jSeparator3.setPreferredSize(new java.awt.Dimension(41, 23));
        jPanel_params.add(jSeparator3);

        buttonGroup1.add(jRadioButton_start);
        jRadioButton_start.setSelected(true);
        jRadioButton_start.setText("Start");
        jPanel_params.add(jRadioButton_start);

        buttonGroup1.add(jRadioButton_end);
        jRadioButton_end.setText("End");
        jRadioButton_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_endActionPerformed(evt);
            }
        });
        jPanel_params.add(jRadioButton_end);

        jPanel_left.add(jPanel_params, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));

        jButton1.setText("Re-plot");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Re-fit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Undo Fit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton7.setText("Full Plot");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setText("Undo-Zoom");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jToggleButton1.setText("Hide Errors");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);

        jButton6.setText("Write Plot File");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton9.setText("Write fitorbit.par");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jToggleButton2.setText("Plot Residuals");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);

        jPanel_left.add(jPanel1, java.awt.BorderLayout.SOUTH);

        jLabel_status.setText("PulsarFitter");
        jPanel2.add(jLabel_status);

        jPanel_left.add(jPanel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel_left, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.updateParams();

        this.replot();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            fitter.loadPar(this.jTextField_par.getText());
            this.jLabel_status.setText("Loaded new par file");
        } catch (IOException ex) {
            this.jLabel_status.setText(ex.getLocalizedMessage());
        }

        replot();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            fitter.loadPer(this.jTextField_per.getText());
            this.jLabel_status.setText("Loaded new per file");
        } catch (IOException ex) {
            this.jLabel_status.setText(ex.getLocalizedMessage());
        }
        replot();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateParams();
        if(this.fitter.refit()){
            this.jLabel_status.setText("Fit Ok");
        } else {
            this.jLabel_status.setText("Fit Failed!");
        }
        replot();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            this.fitter.writeFitPlot(new PrintStream("pulsarfitter.plot"), 128);
            this.jLabel_status.setText("written pulsarfitter.plot");
        } catch (FileNotFoundException ex) {
            this.jLabel_status.setText(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_endActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jRadioButton_endActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.fitter.resetStartEnd();
        this.replot();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        replot();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.jTextField_start.setText(String.valueOf(prevStart));
        this.jTextField_end.setText(String.valueOf(prevEnd));
        replot();

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fitter.undoFit();
        replot();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        fitter.writePar();
        this.jLabel_status.setText("fitorbit.par written");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        replot();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void replot() {

        this.jTextField_period.setText(String.valueOf(fitter.getParams().p0));
        this.jTextField_pdot.setText(String.valueOf(fitter.getParams().p1));
        this.jTextField_pb.setText(String.valueOf(fitter.getParams().pb));
        this.jTextField_x.setText(String.valueOf(fitter.getParams().x));
        this.jTextField_epoch.setText(String.valueOf(fitter.getParams().epoch));
        this.jTextField_tasc.setText(String.valueOf(fitter.getParams().tasc));
        this.jTextField_omega.setText(String.valueOf(fitter.getParams().omega));
        this.jTextField_ecc.setText(String.valueOf(fitter.getParams().e));

        this.jTextField_start.setText(String.valueOf(this.fitter.getStart()));
        this.jTextField_end.setText(String.valueOf(this.fitter.getEnd()));

        this.jPanel_plot.removeAll();
        String ylab = "Period (us) - " + fitter.getParams().p0;
        double[][] xys = this.fitter.getFitCurve(128);
        for (int i = 0; i < xys[0].length; i++) {
            xys[0][i] = xys[0][i] - fitter.getParams().epoch;
            xys[1][i] = (xys[1][i] - fitter.getParams().p0)*1e6;
        }

        double[] mjds = fitter.getPerfile().getMjds();
        double[] periods = fitter.getPerfile().getPeriods();
        for (int i = 0; i < mjds.length; i++) {
            mjds[i] = mjds[i] - fitter.getParams().epoch;
            periods[i] = (periods[i] - fitter.getParams().p0)*1e6;
        }


        if (this.jToggleButton2.isSelected()) {
            double[] modelPeriods = new OrbitalFunction(fitter.getParams()).generateData(fitter.getPerfile().getMjds(), fitter.getParams().getParmArray());
            for (int i = 0; i < mjds.length; i++) {
                periods[i] = (periods[i]/1e6 - (modelPeriods[i] - fitter.getParams().p0))*1e6;
            }
            for (int i = 0; i < xys[0].length; i++) {
                xys[1][i] = 0;
            }
            ylab="Residual (us)";
        }


        final MKPlot plot = new PlotOneDim(fitter.getParfile().getPsrj(), "MJD - " + fitter.getParams().epoch, ylab , xys[0], xys[1], mjds, periods, Color.red, Color.blue);
        plot.setLinestyle(MKPlot.LineStyle.JoinTheDots);
        if (!this.jToggleButton1.isSelected()) {
            double[] errs=this.fitter.getPerfile().getPerrors();
            for (int i = 0; i < mjds.length; i++) {
                errs[i]*=1e6;
            }
            plot.setYErrors(errs);
        }
        plot.addMouseListener(new MouseListener() {

            public void mouseClicked(final MouseEvent e) {
                SwingUtilities.invokeLater(new Runnable() {

                    public void run() {
                        double x = plot.getXPlotPosn(e.getPoint().x);
                        double y = plot.getYPlotPosn(e.getPoint().y);
                        if (e.getButton() == MouseEvent.BUTTON1) {
                            PulsarFitterGui.this.leftClicked(x, y);
                        }
                        if (e.getButton() == MouseEvent.BUTTON3) {
                            double xmin = plot.getXPlotPosn(e.getPoint().x - 16);
                            double ymin = plot.getYPlotPosn(e.getPoint().y + 16);
                            double xmax = plot.getXPlotPosn(e.getPoint().x + 16);
                            double ymax = plot.getYPlotPosn(e.getPoint().y - 16);
//                            plot.setVals(new double[]{xmin, xmin, xmax, xmax}, new double[]{ymin, ymax, ymax, ymin});
                            PulsarFitterGui.this.fitter.getPerfile().delete(x, y, xmin, xmax, ymin, ymax);
                            PulsarFitterGui.this.replot();
                        }
                    }
                });



            }

            public void mousePressed(MouseEvent e) {
            }

            public void mouseReleased(MouseEvent e) {
            }

            public void mouseEntered(MouseEvent e) {
            }

            public void mouseExited(MouseEvent e) {
            }
        });



        this.jPanel_plot.add(plot, BorderLayout.CENTER);
        plot.setVisible(true);
        this.validate();
        this.repaint();
    }

    private void leftClicked(double x, double y) {
        if (this.jRadioButton_start.isSelected()) {
            prevStart = fitter.getStart();
            prevEnd = fitter.getEnd();
            this.jTextField_start.setText(String.valueOf(x + fitter.getParams().epoch));
            this.jRadioButton_end.setSelected(true);
            this.updateParams();
        } else if (this.jRadioButton_end.isSelected()) {
            prevStart = fitter.getStart();
            prevEnd = fitter.getEnd();
            this.jTextField_end.setText(String.valueOf(x + fitter.getParams().epoch));
            this.jRadioButton_start.setSelected(true);
            this.updateParams();
        }
        replot();
    }

    private void rightClicked(double x, double y) {
    }

    private void updateParams() {
        try {
            fitter.getParams().p0 = Double.parseDouble(this.jTextField_period.getText());
            fitter.getParams().p1 = Double.parseDouble(this.jTextField_pdot.getText());
            fitter.getParams().pb = Double.parseDouble(this.jTextField_pb.getText());
            fitter.getParams().x = Double.parseDouble(this.jTextField_x.getText());
            fitter.getParams().epoch = Double.parseDouble(this.jTextField_epoch.getText());
            fitter.getParams().tasc = Double.parseDouble(this.jTextField_tasc.getText());
            fitter.getParams().omega = Double.parseDouble(this.jTextField_omega.getText());
            fitter.getParams().e = Double.parseDouble(this.jTextField_ecc.getText());

            fitter.setStart(Double.parseDouble(this.jTextField_start.getText()));
            fitter.setEnd(Double.parseDouble(this.jTextField_end.getText()));

            fitter.getParams().fitEpoch = this.jCheckBox_epoch.isSelected();
            fitter.getParams().fitP0 = this.jCheckBox_period.isSelected();
            fitter.getParams().fitP1 = this.jCheckBox_pdot.isSelected();
            fitter.getParams().fitPb = this.jCheckBox_pb.isSelected();
            fitter.getParams().fitX = this.jCheckBox_x.isSelected();
            fitter.getParams().fitTasc = this.jCheckBox_tasc.isSelected();
            fitter.getParams().fitOmega = this.jCheckBox_omega.isSelected();
            fitter.getParams().fitE = this.jCheckBox_ecc.isSelected();


        } catch (Exception e) {
            this.jLabel_status.setText("Bad parameter!");

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PulsarFitterGui gui = new PulsarFitterGui();
                if (args.length > 0) {
                    gui.jTextField_par.setText(args[0]);
                    gui.jButton4ActionPerformed(null);
                }
                if (args.length > 1) {
                    gui.jTextField_per.setText(args[1]);
                    gui.jButton5ActionPerformed(null);
                }
                gui.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox_ecc;
    private javax.swing.JCheckBox jCheckBox_epoch;
    private javax.swing.JCheckBox jCheckBox_omega;
    private javax.swing.JCheckBox jCheckBox_pb;
    private javax.swing.JCheckBox jCheckBox_pdot;
    private javax.swing.JCheckBox jCheckBox_period;
    private javax.swing.JCheckBox jCheckBox_tasc;
    private javax.swing.JCheckBox jCheckBox_x;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_head;
    private javax.swing.JPanel jPanel_left;
    private javax.swing.JPanel jPanel_params;
    private javax.swing.JPanel jPanel_plot;
    private javax.swing.JRadioButton jRadioButton_end;
    private javax.swing.JRadioButton jRadioButton_start;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField_ecc;
    private javax.swing.JTextField jTextField_end;
    private javax.swing.JTextField jTextField_epoch;
    private javax.swing.JTextField jTextField_omega;
    private javax.swing.JTextField jTextField_par;
    private javax.swing.JTextField jTextField_pb;
    private javax.swing.JTextField jTextField_pdot;
    private javax.swing.JTextField jTextField_per;
    private javax.swing.JTextField jTextField_period;
    private javax.swing.JTextField jTextField_start;
    private javax.swing.JTextField jTextField_tasc;
    private javax.swing.JTextField jTextField_x;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
